
train_data_path: ../input/demo-template/train.csv
val_data_path: ../input/demo-template/val.csv
test_data_path: ../input/demo-template/train.csv
train_text: tweet
train_label: label
val_text: tweet
val_label: label
test_text: tweet
test_label: label
n_splits: 3
save_model_path: distilbert.bin
finetuned_model_path: distilbert.bin
save_metrics_path: metrics.json
save_metrics_path: metrics.json
save_preds_path: preds.csv